apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mezin
  name: mezin
  namespace: ez
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mezin
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mezin
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
