apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demonginx
  name: demonginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demonginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demonginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
