apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynginxdeployment
  name: mynginxdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginxdeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginxdeployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
